---
environment: production
app_root: /home/someuser/public_html
file_layout: blue_green
default_filesystem: production
mysql_host: 172.31.10.5
mysql_user: acmetunnels
mysql_password: abc123

template_vars:
  database_host: 172.31.10.5
  database_name: acmetunnels
  database_user: acmetunnels
  database_password: abc123
  conductor_environment: prod
  maintenance_whitelist:
    John Smith @ Company1:
      - 50.99.145.222
    Steve Smith @ Compan2:
      - 23.24.145.133
  redis_fpc_host: 172.31.10.5
  redis_fpc_port: 6379
  redis_object_host: 172.31.10.6
  redis_object_port: 6379
  redis_session_host: 172.31.10.7
  redis_session_port: 6379

servers:
  - host: admin
  - host: web1
  - host: web2
