---
environment: local
file_layout: default
default_filesystem: test
mysql_user: dev
mysql_password: password1

databases:
  acmetunnels:
    post_import_scripts:
        - apply-test-settings.sql
        - environment-settings.sql

post_install_scripts:
  magento-build:
    cmd: magento-build
  set-magento-permissions:
    cmd: set-magento-permissions

template_vars:
  database_host: localhost
  database_name: acmetunnels
  database_user: dev
  database_password: password1
  devops_environment: local
  redis_object_host: localhost
  redis_object_port: 6385
  redis_session_host: localhost
  redis_session_port: 6386
  redis_fpc_host: localhost
  redis_fpc_port: 6387

servers:
  - host: localhost
