---
environment: uat
file_layout: branch
default_filesystem: test
mysql_user: dev
mysql_password: password1

databases:
  acmetunnels:
    post_import_scripts:
        - apply-test-settings.sql
        - environment-settings.sql

post_install_scripts:
  magento-build:
    cmd: magento-build
  set-magento-permissions:
    cmd: set-magento-permissions

template_vars:
  database_host: uathost
  database_name: acmetunnels
  database_user: dev
  database_password: password1
  conductor_environment: uat

servers:
  - host: uathost
