---
app_name: Acme Instant Tunnels
app_root: /var/www/acmetunnels
relative_document_root: htdocs
platform: magento1
repo_url: git@bitbucket.org:robofirm/acme-instant-tunnels.git

file_systems:
  test:
    type: aws_s3
    snapshot_root: snapshots
    build_root: builds
    region: us-east-1
    bucket: acmetunnels-test
    profile: test
  production:
    type: aws_s3
    snapshot_root: snapshots
    build_root: builds
    region: us-east-1
    bucket: acmetunnels-production
    profile: production

assets:
  shared/htdocs/media:
    ensure: directory
    excludes:
      - "@magento1_core"

databases:
  acmetunnels:
    excludes:
      - "@magento1_core"
      - custom_table1
      - custom_table2

build_plans:
  development:
    clean_commands:       
      composer-clean: "@composer::clean"
    commands:
      composer-install: "@composer::install-development"
  production:
    commands:
      composer-install: "@composer::install-production"
      \App\BuildCommand\MinifyJsCommand:
        paths: 
          - ./path/to/js
        excludes:
          - cache
    excludes:
      - ./test/custom/exclude

files:
  local/htdocs/var:
    ensure: directory
    mode: 0770
  local/htdocs/app/etc/local.xml:
    ensure: file
    source: app/etc/local.xml.twig
    mode: 0640
    template_vars:
      encryption_key: abc123
  local/htdocs/errors/local.xml:
    ensure: file
    source: errors/local.xml.twig
    mode: 0640
  shared/htdocs/documents:
    ensure: directory
    mode: 0770
  shared/htdocs/feeds:
    ensure: directory
    mode: 0770
  shared/htdocs/var/maintenance-whitelist.txt:
    ensure: file
    source: var/maintenance-whitelist.txt.twig
    mode: 0640
  shared/htdocs/media:
    ensure: directory
    mode: 0770
  local/htdocs/robots.txt:
    ensure: file
    source: robots.txt.twig
    mode: 0640
  shared/htdocs/sitemap:
    ensure: directory
    mode: 0770
  shared/htdocs/system:
    ensure: directory
    mode: 0770
  code/htdocs/app/etc/local.xml:
    ensure: symlink
    target: local/htdocs/app/etc/local.xml
  code/htdocs/documents:
    ensure: symlink
    target: shared/htdocs/documents
  code/htdocs/errors/local.xml:
    ensure: symlink
    target: local/htdocs/errors/local.xml
  code/htdocs/feeds:
    ensure: symlink
    target: shared/htdocs/feeds
  code/htdocs/images:
    ensure: symlink
    target: shared/htdocs/media/images
  code/htdocs/var/maintenance-whitelist.txt:
    ensure: symlink
    target: shared/htdocs/var/maintenance-whitelist.txt
  code/htdocs/media:
    ensure: symlink
    target: shared/htdocs/media
  code/htdocs/robots.txt:
    ensure: symlink
    target: local/htdocs/robots.txt
  code/htdocs/sitemap:
    ensure: symlink
    target: shared/htdocs/sitemap
  code/htdocs/var:
    ensure: symlink
    target: local/htdocs/var

template_vars:
  database_host: localhost
  database_name: acmetunnels
  database_user: acmetunnels
  conductor_app_setup_repo_url: git@bitbucket.org:robofirm/acme-instant-tunnels-app-setup.git
